# Use an official Node.js runtime as a base image
FROM node:14

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the React Native project files to the working directory
COPY . .

# Expose the Metro Bundler port
EXPOSE 8081

# Command to start the development server
CMD ["npx", "react-native", "start"]
